#!/usr/bin/env bun
// Create a GitHub App for caretta's Code Review bot using the GitHub App
// Manifest Flow. Spins up a local Bun server, opens the browser to GitHub's
// app-registration form, then exchanges the returned code for credentials and
// writes them to disk in the locations caretta expects.
//
// Usage:
//   bun scripts/create-github-app.ts
//   GITHUB_ORG=my-org APP_NAME=my-caretta-bot bun scripts/create-github-app.ts

import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

const PORT = Number(process.env.PORT ?? 3000);
const OWNER = process.env.GITHUB_ORG;
const APP_NAME = process.env.APP_NAME ?? "caretta-dev-bot";
const BASE = `http://localhost:${PORT}`;

const CONFIG_DIR = join(homedir(), ".config", "caretta");
const PEM_PATH = join(CONFIG_DIR, "dev-ui-bot.pem");
const ENV_PATH = ".env.github-app";

const manifest = {
  name: APP_NAME,
  url: "https://github.com/geoffsee/caretta",
  hook_attributes: {
    url: `${BASE}/webhook`,
    active: false,
  },
  redirect_url: `${BASE}/callback`,
  callback_urls: [`${BASE}/callback`],
  public: false,
  default_permissions: {
    contents: "read",
    pull_requests: "write",
    issues: "write",
    metadata: "read",
  },
  default_events: [],
};

const state = crypto.randomUUID();

function githubNewAppUrl() {
  return OWNER
    ? `https://github.com/organizations/${OWNER}/settings/apps/new?state=${state}`
    : `https://github.com/settings/apps/new?state=${state}`;
}

async function openBrowser(url: string) {
  const cmd =
    process.platform === "darwin"
      ? ["open", url]
      : process.platform === "win32"
        ? ["cmd", "/c", "start", url]
        : ["xdg-open", url];

  Bun.spawn(cmd, { stdout: "ignore", stderr: "ignore" });
}

const server = Bun.serve({
  port: PORT,
  async fetch(req) {
    const url = new URL(req.url);

    if (url.pathname === "/") {
      const manifestJson = JSON.stringify(manifest).replaceAll("'", "&apos;");
      return new Response(
        `<!doctype html>
<form id="f" action="${githubNewAppUrl()}" method="post">
  <input type="hidden" name="manifest" value='${manifestJson}' />
  <button>Create GitHub App</button>
</form>
<script>document.getElementById("f").submit()</script>`,
        { headers: { "content-type": "text/html" } },
      );
    }

    if (url.pathname === "/callback") {
      if (url.searchParams.get("state") !== state) {
        return new Response("Invalid state", { status: 400 });
      }

      const code = url.searchParams.get("code");
      if (!code) return new Response("Missing code", { status: 400 });

      const res = await fetch(
        `https://api.github.com/app-manifests/${code}/conversions`,
        {
          method: "POST",
          headers: {
            accept: "application/vnd.github+json",
            "x-github-api-version": "2022-11-28",
            "user-agent": "caretta-github-app-manifest",
          },
        },
      );

      if (!res.ok) {
        return new Response(await res.text(), { status: res.status });
      }

      const app = await res.json();

      await mkdir(CONFIG_DIR, { recursive: true, mode: 0o700 });
      await Bun.write(PEM_PATH, app.pem);
      await Bun.$`chmod 600 ${PEM_PATH}`.quiet();

      await Bun.write(
        ENV_PATH,
        [
          `# Generated by scripts/create-github-app.ts on ${new Date().toISOString()}`,
          `# Install the app at ${app.html_url}/installations/new then fill in DEV_BOT_INSTALLATION_ID below.`,
          `DEV_BOT_APP_ID=${app.id}`,
          `DEV_BOT_INSTALLATION_ID=`,
          `DEV_BOT_PRIVATE_KEY=${PEM_PATH}`,
          `# Reference values (not consumed by caretta):`,
          `CLIENT_ID=${app.client_id}`,
          `CLIENT_SECRET=${app.client_secret}`,
          `WEBHOOK_SECRET=${app.webhook_secret}`,
          "",
        ].join("\n"),
      );

      queueMicrotask(() => server.stop());

      return new Response(
        [
          `Created GitHub App: ${app.html_url}`,
          ``,
          `Wrote:`,
          `  ${PEM_PATH}  (private key, chmod 600)`,
          `  ${ENV_PATH}                (DEV_BOT_APP_ID, DEV_BOT_PRIVATE_KEY)`,
          ``,
          `Next steps:`,
          `  1. Install the app on your repo: ${app.html_url}/installations/new`,
          `  2. Copy the installation ID from the URL and set DEV_BOT_INSTALLATION_ID in ${ENV_PATH}.`,
          `  3. source ${ENV_PATH} && caretta`,
          ``,
        ].join("\n"),
        { headers: { "content-type": "text/plain" } },
      );
    }

    return new Response("Not found", { status: 404 });
  },
});

console.log(`Listening on ${BASE} — opening browser…`);
await openBrowser(BASE);
